export enum actionType {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CLEAR_CART = "CLEAR_CART",
  AUTHENTICATE_USER = "AUTHENTICATE_USER",
  UNAUTHENTICATE_USER = "UNAUTHENTICATE_USER",
  AUTO_LOGOUT_USER = "AUTO_LOGOUT_USER",
}
